langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: trusty
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: B9Suy0ItJN+uYN50lvryQ8X0c6y4sEAGbmVMvSibhoYF/kkWGZNWHsaWjtSoTlgQHtpN2a0sQwJZ/2ejn4nBMPP/pJ5RXqoCbrrjM4SA5LlSGtxAVFaWztoBMO7J4gFnclyYefcdBJ92v9etgncJVo/5cgaVu2hSRDy2xiwOBclaA1JQ7gZz0q7ZPxQHMCH5WR55q5LgGe2w8F12Oa/Qjx8VQmn1ZstUGw8hJoXoUVYsj0wTmA+YLa57NkGhtCuKL9QFT4vqVKxwchp2VjXIEwZSxxP7eIocVWb9Zp4tZ/l8xNgOrKBHCVyGzg7MZ+SpacWBShmJOugKZwiEi/IoKg7bWpeBKVTv5Q+ttlIBm+6Wv/iAnhX+ANlQanPpCvconBXQBzyawg40yfSU29Q4DkmNjSteuIKz2jv8kW/okPm5OloZ1m/ohkZLnT6oE/z7bvB2HZmAHe615ncsXU/ao6R3u4EoKx7DOEYG2k04vgRjfUWc84Y9VpMxOt6+QRKnr15zbD5hC+Z1LTu1DE2NHjYtA0bMgNbkPxxRrPMcqIxU+KpmVNxLhLlmgAK17/KczjBxAHxvWpnzaniJK7VoYSo64JZXC3pHtifEVugrWczTL/+jiTAgZct/6FB6O2IRo/butdmmJX+ughVuvSdxGikECsvyI0VM9oZYmpx82JA=
  app: kevin-costner-likes-fields
  on:
    repo: StephanieFriend/brownfield-of-dreams
  skip_cleanup: 'true'
  run: rake db:migrate
